const sedrot = {
    "Achrei Mot" : "אַחֲרֵי מוֹת",
    "Balak" : "בָּלָק",
    "Bamidbar" : "בְּמִדְבַּר",
    "Bechukotai" : "בְּחֻקֹּתַי",
    "Beha'alotcha" : "בְּהַעֲלֹתְךָ",
    "Behar" : "בְּהַר",
    "Bereshit" : "בְּרֵאשִׁית",
    "Beshalach" : "בְּשַׁלַּח",
    "Bo" : "בֹּא",
    "Chayei Sara" : "חַיֵּי שָֹרָה",
    "Chukat" : "חֻקַּת",
    "Devarim" : "דְּבָרִים",
    "Eikev" : "עֵקֶב",
    "Emor" : "אֱמוֹר",
    "Ha'Azinu" : "הַאֲזִינוּ",
    "Kedoshim" : "קְדשִׁים",
    "Ki Tavo" : "כִּי־תָבוֹא",
    "Ki Teitzei" : "כִּי־תֵצֵא",
    "Ki Tisa" : "כִּי תִשָּׂא",
    "Korach" : "קוֹרַח",
    "Lech-Lecha" : "לֶךְ־לְךָ",
    "Masei" : "מַסְעֵי",
    "Matot" : "מַּטּוֹת",
    "Metzora" : "מְּצֹרָע",
    "Miketz" : "מִקֵּץ",
    "Mishpatim" : "מִּשְׁפָּטִים",
    "Nasso" : "נָשׂא",
    "Nitzavim" : "נִצָּבִים",
    "Noach" : "נֹחַ",
    "Pekudei" : "פְקוּדֵי",
    "Pinchas" : "פִּינְחָס",
    "Re'eh" : "רְאֵה",
    "Sh'lach" : "שְׁלַח־לְךָ",
    "Shemot" : "שְׁמוֹת",
    "Shmini" : "שְּׁמִינִי",
    "Shoftim" : "שׁוֹפְטִים",
    "Tazria" : "תַזְרִיעַ",
    "Terumah" : "תְּרוּמָה",
    "Tetzaveh" : "תְּצַוֶּה",
    "Toldot" : "תּוֹלְדוֹת",
    "Tzav" : "צַו",
    "Vaera" : "וָאֵרָא",
    "Vaetchanan" : "וָאֶתְחַנַּן",
    "Vayakhel" : "וַיַּקְהֵל",
    "Vayechi" : "וַיְחִי",
    "Vayeilech" : "וַיֵּלֶךְ",
    "Vayera" : "וַיֵּרָא",
    "Vayeshev" : "וַיֵּשֶׁב",
    "Vayetzei" : "וַיֵּצֵא",
    "Vayigash" : "וַיִּגַּשׁ",
    "Vayikra" : "וַיִּקְרָא",
    "Vayishlach" : "וַיִּשְׁלַח",
    "Vezot Haberakhah" : "וְזֹאת הַבְּרָכָה",
    "Yitro" : "יִתְרוֹ"
};

const holidays = {
    "Asara B'Tevet" : "עֲשָׂרָה בְּטֵבֵת",
    "Candle lighting" : "הדלקת נרות",
    "Chanukah" : "חֲנוּכָּה",
    "Havdalah" : "הַבדָלָה",
    "Lag BaOmer" : "ל״ג בְּעוֹמֶר",
    "Leil Selichot" : "סליחות",
    "Pesach" : "פֶּסַח",
    "Pesach Sheni" : "פֶּסַח שני",
    "Purim" : "פּוּרִים",
    "Purim Katan" : "פּוּרִים קָטָן",
    "Rosh Chodesh Adar" : "רֹאשׁ חודש אַדָר",
    "Rosh Chodesh Adar I" : "רֹאשׁ חודש אַדָר א׳",
    "Rosh Chodesh Adar II" : "רֹאשׁ חודש אַדָר ב׳",
    "Rosh Chodesh Av" : "רֹאשׁ חודש אָב",
    "Rosh Chodesh Cheshvan" : "רֹאשׁ חודש חֶשְׁוָן",
    "Rosh Chodesh Elul" : "רֹאשׁ חודש אֱלוּל",
    "Rosh Chodesh Iyyar" : "רֹאשׁ חודש אִיָיר",
    "Rosh Chodesh Kislev" : "רֹאשׁ חודש כִּסְלֵו",
    "Rosh Chodesh Nisan" : "רֹאשׁ חודש נִיסָן",
    "Rosh Chodesh Sh'vat" : "רֹאשׁ חודש שְׁבָט",
    "Rosh Chodesh Sivan" : "רֹאשׁ חודש סִיוָן",
    "Rosh Chodesh Tamuz" : "רֹאשׁ חודש תָּמוּז",
    "Rosh Chodesh Tevet" : "רֹאשׁ חודש טֵבֵת",
    "Rosh Hashana" : "רֹאשׁ הַשָּׁנָה",
    "Shabbat Chazon" : "שַׁבָּת חֲזוֹן",
    "Shabbat HaChodesh" : "שַׁבָּת הַחֹדֶשׁ",
    "Shabbat HaGadol" : "שַׁבָּת הַגָּדוֹל",
    "Shabbat Machar Chodesh" : "שבת מחר חודש",
    "Shabbat Nachamu" : "שַׁבָּת נַחֲמוּ",
    "Shabbat Parah" : "שַׁבָּת פּרה",
    "Shabbat Rosh Chodesh" : "שבת ראש חודש",
    "Shabbat Shekalim" : "שַׁבָּת שְׁקָלִים",
    "Shabbat Shuva" : "שַׁבָּת שׁוּבָה",
    "Shabbat Zachor" : "שַׁבָּת זָכוֹר",
    "Shavuot" : "שָׁבוּעוֹת",
    "Shmini Atzeret" : "שְׁמִינִי עֲצֶרֶת",
    "Shushan Purim" : "שׁוּשָׁן פּוּרִים",
    "Sigd" : "סיגד",
    "Simchat Torah" : "שִׂמְחַת תּוֹרָה",
    "Sukkot" : "סוּכּוֹת",
    "Ta'anit Bechorot" : "תַּעֲנִית בְּכוֹרוֹת",
    "Ta'anit Esther" : "תַּעֲנִית אֶסְתֵּר",
    "Tish'a B'Av" : "תִּשְׁעָה בְּאָב",
    "Tu B'Av" : "טוּ בְּאָב",
    "Tu BiShvat" : "טוּ בִּשְׁבָט",
    "Tzom Gedaliah" : "צוֹם גְּדַלְיָה",
    "Tzom Tammuz" : "צוֹם תָּמוּז",
    "Yom HaAtzma'ut" : "יוֹם הָעַצְמָאוּת",
    "Yom HaShoah" : "יוֹם הַשּׁוֹאָה",
    "Yom HaZikaron" : "יוֹם הַזִּכָּרוֹן",
    "Yom Kippur" : "יוֹם כִּפּוּר",
    "Yom Yerushalayim" : "יוֹם יְרוּשָׁלַיִם"
};

module.exports = {
	sedrot,
	holidays
};
